"""rename department

Revision ID: 458ea643186e
Revises: ef006d6bb9e7
Create Date: 2026-01-12 11:59:36.305199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458ea643186e'
down_revision = 'ef006d6bb9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###